stages:
  - lint
  - test
  - package
  - doc

.setup_venv: &setup_venv
  - python3 -m venv .venv
  - source .venv/bin/activate
  - pip install .[dev]

lint:
  stage: lint
  dependencies: []
  script:
    - *setup_venv
    - pip install pylint-gitlab
    # call ruff twice as there is no option to print output and generate report
    - ruff check || true
    - ruff  --output-format=gitlab --output-file=codequality-ruff.json || true
    - |
      pylint \
          --exit-zero --load-plugins=pylint_gitlab \
          --output-format=gitlab-codeclimate:codequality-pylint.json,text labgrid
  artifacts:
    reports:
      codequality: codequality-*.json

test:
  stage: test
  dependencies: []
  allow_failure: true
  script:
    # set localhost known_hosts to current localhost
    - *setup_venv
    - ssh-keygen -f "$HOME/.ssh/known_hosts" -R "localhost" || true
    - ssh -o StrictHostKeyChecking=no localhost true
    - |
      pytest \
          --cov-config .coveragerc --cov=labgrid \
          --junit-xml=junit.xml \
          --local-sshmanager --ssh-username $(whoami) \
          -k "not test_docker_with_daemon and not test_remote_managedfile and not test_import_backend_eaton and not test_import_backend_poe_mib"
  coverage: '/TOTAL.+ ([0-9]{1,3}%)/'
  artifacts:
    reports:
      junit: junit.xml


.gbp_package_script: &gbp_package_script
  - git fetch origin mle/${DIST}/v24.0.0+mle
  - git branch -a
  - mkdir $TEMPDIR
  - cd $TEMPDIR
  - git clone .. . --branch mle/${DIST}/v24.0.0+mle
  - git branch -a
  - git rebase ${CI_COMMIT_REF_SLUG}
  - dch --increment --distribution jammy "ci build from ${CI_COMMIT_REF_SLUG}"
  - git add debian/changelog
  - git commit -m"changelog for ${CI_COMMIT_REF_SLUG}"
  - gbp buildpackage

package:jammy:
  stage: package
  dependencies: []
  variables:
    TEMPDIR: "tempdir"
    DIST: ubuntu-jammy
  script:
    - *gbp_package_script

package:noble:
  stage: package
  dependencies: []
  variables:
    TEMPDIR: "tempdir"
    DIST: ubuntu-noble
  script:
    - *gbp_package_script

pages:
  stage: doc
  dependencies: []
  script:
    - *setup_venv
    - sphinx-build -b html doc public
  artifacts:
    paths:
      - public
